### ISSUE TITLE
Error con las pruebas del servidor

### ISSUE THREAD

**Issue by alu0101205953** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct10-async-sockets-alu0101205953#1]
Buenas. @esegredo @amarrerod 
He estado tratando de realizar las pruebas del servidor desarrollado en la práctica. El problema está en que cuando trato de hacer una prueba para la funcionalidad de añadir una nota recibo este error y no encuentro la manera de resolverlo: 
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by esegredo** [comment]
Hola @alu0101205953 , buenas tardes.

El manejador que recibe la función it de Chai, tiene como argumento una función done, que debes invocar dentro de los manejadores que registras para algún evento de una operación asíncrona. Fíjate en los apuntes, en concreto, en la última sección de pruebas con Mocha y Chai del apartado de Sockets.

```typescript
import 'mocha';
import {expect} from 'chai';
import {EventEmitter} from 'events';
import {MessageEventEmitterClient} from '../src/eventEmitterClient';

describe('MessageEventEmitterClient', () => {
  it('Should emit a message event once it gets a complete message', (done) => {
    const socket = new EventEmitter();
    const client = new MessageEventEmitterClient(socket);

    client.on('message', (message) => {
      expect(message).to.be.eql({'type': 'change', 'prev': 13, 'curr': 26});
      done();
    });

    socket.emit('data', '{"type": "change", "prev": 13');
    socket.emit('data', ', "curr": 26}');
    socket.emit('data', '\n');
  });
});
```

Saludos.
